Repository planetarium/lib9c-wasm, pull requests merged in 2023-05, with the labels that each got.

#24 Deprecated `lib9c-wasm/tx` feature
  Lib9c.Wasm/Program.cs
  Lib9c.Wasm/RawTransaction.cs
  Lib9c.Wasm/RawUnsignedTransaction.cs
  Lib9c.Wasm/TransactionSerializationConstants.cs
  generate.ts
Labels: Medium

#26 Clean code
  Lib9c.Wasm/JsonUtils.cs
  Lib9c.Wasm/Program.cs
  examples/claim_stake_reward.ts
  examples/hack_and_slash.ts
  examples/stake.ts
  examples/transfer_asset.ts
  generate.ts
  package.json
  static/utils.ts
  test.ts
Labels: Medium

#27 ci(gh-actions): add build workflow
  .github/workflows/build.yaml
Labels: Extra Small

#28 ci(gh-actions): introduce deploy workflow
  .github/workflows/deploy.yaml
  .yarn/releases/yarn-3.2.4.cjs
  .yarn/releases/yarn-3.5.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: Extra Small

#29 docs: update readme badge
  README.md
Labels: documentation, Extra Small

#30 docs: update package name
  README.md
Labels: documentation

#34 Several patches
  .github/workflows/deploy.yaml
  Lib9c.Wasm/Program.cs
  package.json
  patch.ts
Labels: Extra Small

#35 Remove node:buffer usage and redundant dependencies
  package.json
  static/utils.ts
  yarn.lock
Labels: enhancement
